# Resolve react_native_pods.rb with node to allow for hoisting

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
  
platform :ios, '11.0'
# prepare_react_native_project!

# linkage = ENV['USE_FRAMEWORKS']
# if linkage != nil
#   Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
#   use_frameworks! :linkage => linkage.to_sym
# end

target 'SsTrackingSdkRnExample' do
  config = use_native_modules!

  use_react_native!(:path => config[:reactNativePath])

  pod 'ss-tracking-sdk-rn', :path => "../node_modules/ss-tracking-sdk-rn"

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
        deployment_target = config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']
        target_components = deployment_target.split
        if target_components.length > 0
          target_initial = target_components[0].to_i
          if target_initial < 9
            config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = '11.0'
          end
        end
      end
    end
  end
  # config = use_native_modules!

  # use_react_native!(
  #   :path => config[:reactNativePath],
  #   # An absolute path to your application root.
  #   :app_path => "#{Pod::Config.instance.installation_root}/.."
  # )

  # target 'SsTrackingSdkRnExampleTests' do
  #   inherit! :complete
  #   # Pods for testing
  # end

  # post_install do |installer|
  #   # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
  #   react_native_post_install(
  #     installer,
  #     config[:reactNativePath],
  #     :mac_catalyst_enabled => false,
  #     # :ccache_enabled => true
  #   )
  # end
end
